version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www
    depends_on:
      - database
    networks:
      - car-credit

  web:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - car-credit

  database:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_DATABASE: car_credit
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - car-credit

volumes:
  database_data:

networks:
  car-credit: